### PR TITLE
Add $object parameter to avoid a PHP warning

### PR DESCRIPTION
**Pull request by vincentlepot**
When installing in a fresh instance of NMM, we experience a warning which is blocking in certain configurations of Symfony.

```
Warning: Declaration of Tisseo\CoreBundle\Controller\CoreController::isGranted($permission) should be compatible with Symfony\Bundle\FrameworkBundle\Controller\Controller::isGranted($attributes, $object = NULL) in /var/www/html/vendor/tisseo/core-bundle/Controller/CoreController.php on line 11
```

I propose this patch to avoid the warning, even if IMHO it would be better to rely on the implementation of the base Controller class, or use another method name since it's not acting the same way (the base implementation returns a boolean).

### CODE REVIEW

**Comment by vpassama** [comment]
Hi @vincentlepot ,

The new version I'm updating now, doesn't contain any of these functions because it is not a good practice. 
Now all bundles use the symfony isGranted and denyAccessUnlessIsGranted.

Let me now if it does the job.

**Comment by vincentlepot** [comment]
I agree it will be better. Keep me updated when the version is available :)

**Comment by vpassama** [comment]
This is updated.

**Comment by vincentlepot** [comment]
Great, I will upgrade my installation then.

**Pull request closed without merging**
